### PR TITLE
Fixes for Custom Column Names

### PR DESCRIPTION
**Pull request by ryanhalliday**
The unit tests didn't cover everything, so when trying to use this there were some errors with the escaping occurring for the query parameter identifiers too.
I have fixed this with some restructuring of the functions.

### CODE REVIEW

**Comment by cryptiklemur** [comment]
+1

Please merge. Unusable without this

**Comment by cryptiklemur** [comment]
@jasongrimes Please merge this. Its been several months now.

**Comment by ryanhalliday** [comment]
Unfortunately I think this project has been abandoned. This project has strange structure and implementation anyway...

Here are three better solutions than this project:
- Use some external OAuth system that is relevant.
- Some other more generic authentication library (Symfony Security, Sentry etc.)
- Roll your own, be sure to use [password_hash](https://secure.php.net/manual/en/function.password-hash.php) and [good security practices](http://www.phptherightway.com/#security).

**Comment by ryanhalliday** [comment]
Repo is dead. Closing PR

**Pull request closed without merging**
