### PR TITLE
Fix: fixed security issue where login form is not protected against CSRF attacks

### PR DESCRIPTION
**Pull request by deanc**
This is the first step in a fix for #29

### CODE REVIEW

**Comment by deanc** [comment]
Consider this a WIP until I have fixed all forms!

**Comment by deanc** [comment]
This is beginning to get complicated. I managed to refactor the registration form substantially, but in implementing the password field I stumbled across this BC break in SF2's form component:
https://github.com/symfony/symfony/issues/12792

So until they merge this fix I can't actually use the `repeated` field type for the password field. So I have two choices: a) wait or b) use two standard text fields and compare the input as you were doing before. I would *prefer* not to do this incorrectly and use the `repeated` field type, but it's going to delay this pull request.

In theory I could keep this PR as a fix for the login form CSRF and we could work on the other forms as individual PR's too.

**Comment by deanc** [comment]
As discussed, this can now be merged as an urgent security fix. I will work on the abstraction of forms as a separate branch.

**Comment by deanc** [comment]
On your demo app, this breaks the registration form. I'm testing at the moment.

**Comment by jasongrimes** [comment]
I created a new 3.0 branch  ("3.0.x-dev" in composer) for BC-breaking changes. Would you mind issuing a new pull request against that branch? Thanks again for this important work.

**Comment by rsantellan** [comment]
I have downloaded the 3.0 branch and on the login after I remove the csrf token in the html no error is shown on submit. 
I should add something more than the 
<input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}" />

and 

$app['security.firewalls'] = array(
    'login' => array(
        'pattern' => '^/user/login$',
        'anonymous' => true,
    ),
    'register' => array(
        'pattern' => '^/register$',
        
    ),
    'callcenter' => array(
        'pattern' => '^.*$',
        'anonymous' => false,
        'form' => array(
            'login_path' => '/user/login', 
            'check_path' => '/user/login_check', 
            'csrf_provider' => 'form.csrf_provider',
        ),
        'logout' => array(
            'logout_path' => '/user/logout',
        ),
        'users' => $app->share(function($app) { return $app['user.manager']; }),
    ),
);

Regards

**Comment by theobe** [comment]
I've the same problem as rsantellan.
Checking the code of the Silex Security Provider learns me that you have to add an extra option 'with_csrf'.

Your config should look like this:

```
'secured_area' => array(
    'pattern' => '^.*$',
    'anonymous' => false,
    'form' => array(
        'login_path' => '/user/login', 
        'check_path' => '/user/login_check', 
        'csrf_provider' => 'form.csrf_provider',
        'with_csrf' => true,
    ),
    'logout' => array(
        'logout_path' => '/user/logout',
    ),
    'users' => $app->share(function($app) { return $app['user.manager']; }),
),
```

Regards

**Pull request closed without merging**
